name: client
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: teja <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  jaguar_resty: ^1.1.5
  server:
    path: ../server

dev_dependencies:
  build_runner:
  build_web_compilers:

web:
  compiler:
    debug: dartdevc
