name: server
description: Server package for Omnialarm
version: 0.0.1
#homepage: https://www.example.com
#author: teja <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar: ^1.3.11
  jaguar_auth: ^1.3.0
  mongo_dart: ^0.3.1
  jaguar_mongo: ^1.3.1
  jaguar_reflect: ^1.3.0
  jaguar_validate: #^1.0.0
    path: ../../jaguar/jaguar_validate
  jaguar_dev_proxy:

dev_dependencies:
  test: ^0.12.0
